name: simple
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pillow
  - tqdm
  - pyyaml
  - matplotlib
  - future
  - h5py
  - numpy
  - matplotlib
  - plotly
  - pandas
  - scipy
  - scikit-learn
  - cudatoolkit=10.2
  - pytorch::torchvision
  - pytorch::pytorch=1.6.0
  - pip:
      - kornia==0.5.0
      - wandb
